### ISSUE TITLE
Cannot find the MSI for Release 3.3.225.0

### ISSUE THREAD

**Issue by atfriberg** [PureStorage-OpenConnect/powershell-toolkit#14]
Cannot find the MSI for Release 3.3.225.0

**Comment by barkz** [comment]
Is there a particular need for the MSI? I switched over distribution of the Pure Storage [PowerShell Toolkit](https://www.powershellgallery.com/packages/PureStoragePowerShellToolkit) and [PowerShell SDK](https://www.powershellgallery.com/packages/PureStoragePowerShellSDK) to the PowerShell Gallery.

**Comment by atfriberg** [comment]
Thank you.  Got it!


Tony Friberg
Sr. Solutions Engineer | Solutions II, Inc.


401 East Sonterra Blvd, Suite 220 | San Antonio, Texas 78258
Phone (Single-Reach): 210.201.8016 | Fax: 210.403.3336


www.Solutions-ii.com<http://www.solutions-ii.com/> | Integrity, Passion, Quality

**Comment by barkz** [comment]
Closing as resolved per discussion. Thanks.
