### ISSUE TITLE
New-FlashArrayCapacityReport does not run due to error on 152:3

### ISSUE THREAD

**Issue by dstamen** [PureStorage-OpenConnect/PowerShell-Toolkit#28]
PS C:\Users\dstamen> New-FlashArrayCapacityReport -EndPoint $pureendpoint -Credential $purecred -VolumeFilter '*ds3*' -OutFilePath .\ -HTMLFileName Test.html
Cannot convert value ":1" to type "System.Decimal". Error: "Input string was not in a correct format."
At C:\Program Files\WindowsPowerShell\Modules\PureStoragePowerShellToolkit\1903.7\PureStoragePowerShellToolkit.psm1:152 char:3
+         $sysTotalDRR = [system.Math]::Round($FlashArraySpaceMetrics.t ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToDecima

![image](https://user-images.githubusercontent.com/11834898/89441036-86dd6800-d71a-11ea-9bf7-ca3663e070ea.png)

i was able to modify that line to be a standard variable and it proceeded, so something in the getting of the DDR is failing. this occured in PS5,6,7 on windows 10 and windows server.

**Comment by mikenelson-io** [comment]
Updated in 2.0.1.0.
