### ISSUE TITLE
Merge PureStorageDbaTools module

### ISSUE THREAD

**Issue by barkz** [PureStorage-OpenConnect/PowerShell-Toolkit#47]
Merge below cmdlets into the Toolkit to centralize for distribution.

- New-PfaDbSnapshot
- Invoke-PfaDbRefresh
- Enable-DataMasks
- Invoke-StaticDataMasking
- Invoke-DynamicDataMasking

**Comment by mikenelson-io** [comment]
Merged into branch 2.0.1.0.
The function Enable-Datamasks was previously deprecated and not merged.

**Comment by mikenelson-io** [comment]
Branch has not yet merged with dev branch. More edits to come before final merge.
